# Generated by Django 4.2.11 on 2024-04-16 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emp_register', '0002_employee_email_alter_employee_emp_code'),
        ('emp_register', '0004_alter_employee_email'),
    ]

    operations = [
    ]
