# Generated by Django 4.2.11 on 2024-04-17 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emp_register', '0006_employee_emp_registe_fullnam_102cb3_idx'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='employee',
            name='emp_registe_fullnam_102cb3_idx',
        ),
    ]
