# Generated by Django 4.2.11 on 2024-05-01 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp_register', '0008_employee_emp_registe_fullnam_102cb3_idx'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='employee',
            name='emp_registe_fullnam_102cb3_idx',
        ),
        migrations.AlterField(
            model_name='employee',
            name='emp_code',
            field=models.CharField(db_index=True, max_length=4),
        ),
    ]
